### ISSUE TITLE
new query

### ISSUE THREAD

**Issue by kompo7** [microsoft/Microsoft-365-Defender-Hunting-Queries#237]
Hi all,

Could you please provide a query that looks if a certain software is installed on a machine and print the result of machines that don't have the software

Thanks

**Comment by A-dd-Y** [comment]
DeviceFileEvents
| where FileName !has "nmap.exe"
| summarize count() by DeviceName
| sort by count_

**Comment by tali-ash** [comment]
You can use the new table of **DeviceTvmSoftwareInventory**.
This table will serve as a complete list of all software on your devices, whether or not they have any vulnerabilities.  
No duplicate entries – unlike the old table, you’ll have a single row for each software installed on every device. 
New fields – ‘EndOfSupportStatus’ and ‘EndOfSupportDate’ will have the end-of-support state (if applicable) for specific software versions installed on devices. 

All details at  [https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/advanced-hunting-updates-to-threat-and-vulnerability-management/ba-p/2162584](url)
