### ISSUE TITLE
Protection | Windows Filtering Events

### ISSUE THREAD

**Issue by SmittySec** [microsoft/Microsoft-365-Defender-Hunting-Queries#307]
@TomerAlpert @makislev 
Has there been a change in event forwarding?  This query is no longer returning any ActionTypes - re: Firewall.  
https://github.com/microsoft/Microsoft-365-Defender-Hunting-Queries/blob/master/Protection%20events/Windows%20filtering%20events%20(Firewall).txt
// Get all filtering events done by the Windows filtering platform.
// This includes any blocks done by Windows Firewall rules, but also blocks triggered by some 3rd party firewalls.
// When no Firewall rules are configured, the default behavior is to block all incoming network connections.
DeviceEvents
| where ActionType in ("FirewallOutboundConnectionBlocked", "FirewallInboundConnectionBlocked", "FirewallInboundConnectionToAppBlocked")
| project DeviceId , Timestamp , InitiatingProcessFileName , InitiatingProcessParentFileName, RemoteIP, RemotePort, LocalIP, LocalPort
| summarize MachineCount=dcount(DeviceId) by RemoteIP
| top 100 by MachineCount desc

Thanks, 

Rich

**Comment by A-dd-Y** [comment]
Query is working fine, you can run below query to check if three action type **("FirewallOutboundConnectionBlocked", "FirewallInboundConnectionBlocked", "FirewallInboundConnectionToAppBlocked")** shows up in results or not

```
DeviceEvents
| summarize count() by ActionType
| sort by ActionType asc
```
