### ISSUE TITLE
Query for Country code

### ISSUE THREAD

**Issue by nicolas-gagnon** [microsoft/Microsoft-365-Defender-Hunting-Queries#332]
Hi i try to write a query to  see any communication from specific country. 
Example
I would like to see if there is any network activity from russia by example or any country

**Comment by A-dd-Y** [comment]
union IdentityLogonEvents, DeviceNetworkEvents
| summarize count() by DeviceName, Location
| limit 10

**Comment by nicolas-gagnon** [comment]
thx you  for the quick answer
